// Code generated by mockery. DO NOT EDIT.

package filter

import mock "github.com/stretchr/testify/mock"

// MockClause is an autogenerated mock type for the Clause type
type MockClause struct {
	mock.Mock
}

type MockClause_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClause) EXPECT() *MockClause_Expecter {
	return &MockClause_Expecter{mock: &_m.Mock}
}

// Type provides a mock function with no fields
func (_m *MockClause) Type() ClauseType {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 ClauseType
	if rf, ok := ret.Get(0).(func() ClauseType); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ClauseType)
	}

	return r0
}

// MockClause_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockClause_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockClause_Expecter) Type() *MockClause_Type_Call {
	return &MockClause_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockClause_Type_Call) Run(run func()) *MockClause_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClause_Type_Call) Return(_a0 ClauseType) *MockClause_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClause_Type_Call) RunAndReturn(run func() ClauseType) *MockClause_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClause creates a new instance of MockClause. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClause(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClause {
	mock := &MockClause{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
