// Code generated by mockery. DO NOT EDIT.

package filter

import mock "github.com/stretchr/testify/mock"

// MockCrudFilter is an autogenerated mock type for the CrudFilter type
type MockCrudFilter struct {
	mock.Mock
}

type MockCrudFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCrudFilter) EXPECT() *MockCrudFilter_Expecter {
	return &MockCrudFilter_Expecter{mock: &_m.Mock}
}

// AcceptVisitor provides a mock function with given fields: _a0
func (_m *MockCrudFilter) AcceptVisitor(_a0 Visitor) (Clause, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AcceptVisitor")
	}

	var r0 Clause
	var r1 error
	if rf, ok := ret.Get(0).(func(Visitor) (Clause, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(Visitor) Clause); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Clause)
		}
	}

	if rf, ok := ret.Get(1).(func(Visitor) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCrudFilter_AcceptVisitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptVisitor'
type MockCrudFilter_AcceptVisitor_Call struct {
	*mock.Call
}

// AcceptVisitor is a helper method to define mock.On call
//   - _a0 Visitor
func (_e *MockCrudFilter_Expecter) AcceptVisitor(_a0 interface{}) *MockCrudFilter_AcceptVisitor_Call {
	return &MockCrudFilter_AcceptVisitor_Call{Call: _e.mock.On("AcceptVisitor", _a0)}
}

func (_c *MockCrudFilter_AcceptVisitor_Call) Run(run func(_a0 Visitor)) *MockCrudFilter_AcceptVisitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Visitor))
	})
	return _c
}

func (_c *MockCrudFilter_AcceptVisitor_Call) Return(_a0 Clause, _a1 error) *MockCrudFilter_AcceptVisitor_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCrudFilter_AcceptVisitor_Call) RunAndReturn(run func(Visitor) (Clause, error)) *MockCrudFilter_AcceptVisitor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCrudFilter creates a new instance of MockCrudFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCrudFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCrudFilter {
	mock := &MockCrudFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
