// Code generated by mockery. DO NOT EDIT.

package filter

import mock "github.com/stretchr/testify/mock"

// MockVisitor is an autogenerated mock type for the Visitor type
type MockVisitor struct {
	mock.Mock
}

type MockVisitor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVisitor) EXPECT() *MockVisitor_Expecter {
	return &MockVisitor_Expecter{mock: &_m.Mock}
}

// VisitConditional provides a mock function with given fields: _a0
func (_m *MockVisitor) VisitConditional(_a0 *ConditionalFilter) (Clause, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitConditional")
	}

	var r0 Clause
	var r1 error
	if rf, ok := ret.Get(0).(func(*ConditionalFilter) (Clause, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*ConditionalFilter) Clause); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Clause)
		}
	}

	if rf, ok := ret.Get(1).(func(*ConditionalFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVisitor_VisitConditional_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitConditional'
type MockVisitor_VisitConditional_Call struct {
	*mock.Call
}

// VisitConditional is a helper method to define mock.On call
//   - _a0 *ConditionalFilter
func (_e *MockVisitor_Expecter) VisitConditional(_a0 interface{}) *MockVisitor_VisitConditional_Call {
	return &MockVisitor_VisitConditional_Call{Call: _e.mock.On("VisitConditional", _a0)}
}

func (_c *MockVisitor_VisitConditional_Call) Run(run func(_a0 *ConditionalFilter)) *MockVisitor_VisitConditional_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ConditionalFilter))
	})
	return _c
}

func (_c *MockVisitor_VisitConditional_Call) Return(_a0 Clause, _a1 error) *MockVisitor_VisitConditional_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVisitor_VisitConditional_Call) RunAndReturn(run func(*ConditionalFilter) (Clause, error)) *MockVisitor_VisitConditional_Call {
	_c.Call.Return(run)
	return _c
}

// VisitLogical provides a mock function with given fields: _a0
func (_m *MockVisitor) VisitLogical(_a0 *LogicalFilter) (Clause, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitLogical")
	}

	var r0 Clause
	var r1 error
	if rf, ok := ret.Get(0).(func(*LogicalFilter) (Clause, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*LogicalFilter) Clause); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Clause)
		}
	}

	if rf, ok := ret.Get(1).(func(*LogicalFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVisitor_VisitLogical_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitLogical'
type MockVisitor_VisitLogical_Call struct {
	*mock.Call
}

// VisitLogical is a helper method to define mock.On call
//   - _a0 *LogicalFilter
func (_e *MockVisitor_Expecter) VisitLogical(_a0 interface{}) *MockVisitor_VisitLogical_Call {
	return &MockVisitor_VisitLogical_Call{Call: _e.mock.On("VisitLogical", _a0)}
}

func (_c *MockVisitor_VisitLogical_Call) Run(run func(_a0 *LogicalFilter)) *MockVisitor_VisitLogical_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*LogicalFilter))
	})
	return _c
}

func (_c *MockVisitor_VisitLogical_Call) Return(_a0 Clause, _a1 error) *MockVisitor_VisitLogical_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVisitor_VisitLogical_Call) RunAndReturn(run func(*LogicalFilter) (Clause, error)) *MockVisitor_VisitLogical_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVisitor creates a new instance of MockVisitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVisitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVisitor {
	mock := &MockVisitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
