// Code generated by mockery. DO NOT EDIT.

package parser

import (
	mock "github.com/stretchr/testify/mock"
	filter "go.lumeweb.com/queryutil/filter"
)

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// ParseFilters provides a mock function with no fields
func (_m *MockParser) ParseFilters() ([]filter.CrudFilter, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ParseFilters")
	}

	var r0 []filter.CrudFilter
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]filter.CrudFilter, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []filter.CrudFilter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]filter.CrudFilter)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParser_ParseFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseFilters'
type MockParser_ParseFilters_Call struct {
	*mock.Call
}

// ParseFilters is a helper method to define mock.On call
func (_e *MockParser_Expecter) ParseFilters() *MockParser_ParseFilters_Call {
	return &MockParser_ParseFilters_Call{Call: _e.mock.On("ParseFilters")}
}

func (_c *MockParser_ParseFilters_Call) Run(run func()) *MockParser_ParseFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParser_ParseFilters_Call) Return(_a0 []filter.CrudFilter, _a1 error) *MockParser_ParseFilters_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParser_ParseFilters_Call) RunAndReturn(run func() ([]filter.CrudFilter, error)) *MockParser_ParseFilters_Call {
	_c.Call.Return(run)
	return _c
}

// ParsePagination provides a mock function with no fields
func (_m *MockParser) ParsePagination() (filter.Pagination, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ParsePagination")
	}

	var r0 filter.Pagination
	var r1 error
	if rf, ok := ret.Get(0).(func() (filter.Pagination, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() filter.Pagination); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(filter.Pagination)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParser_ParsePagination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParsePagination'
type MockParser_ParsePagination_Call struct {
	*mock.Call
}

// ParsePagination is a helper method to define mock.On call
func (_e *MockParser_Expecter) ParsePagination() *MockParser_ParsePagination_Call {
	return &MockParser_ParsePagination_Call{Call: _e.mock.On("ParsePagination")}
}

func (_c *MockParser_ParsePagination_Call) Run(run func()) *MockParser_ParsePagination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParser_ParsePagination_Call) Return(_a0 filter.Pagination, _a1 error) *MockParser_ParsePagination_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParser_ParsePagination_Call) RunAndReturn(run func() (filter.Pagination, error)) *MockParser_ParsePagination_Call {
	_c.Call.Return(run)
	return _c
}

// ParseSorts provides a mock function with given fields: _a0
func (_m *MockParser) ParseSorts(_a0 *filter.SortConfig) ([]filter.Sort, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ParseSorts")
	}

	var r0 []filter.Sort
	var r1 error
	if rf, ok := ret.Get(0).(func(*filter.SortConfig) ([]filter.Sort, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*filter.SortConfig) []filter.Sort); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]filter.Sort)
		}
	}

	if rf, ok := ret.Get(1).(func(*filter.SortConfig) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParser_ParseSorts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseSorts'
type MockParser_ParseSorts_Call struct {
	*mock.Call
}

// ParseSorts is a helper method to define mock.On call
//   - _a0 *filter.SortConfig
func (_e *MockParser_Expecter) ParseSorts(_a0 interface{}) *MockParser_ParseSorts_Call {
	return &MockParser_ParseSorts_Call{Call: _e.mock.On("ParseSorts", _a0)}
}

func (_c *MockParser_ParseSorts_Call) Run(run func(_a0 *filter.SortConfig)) *MockParser_ParseSorts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*filter.SortConfig))
	})
	return _c
}

func (_c *MockParser_ParseSorts_Call) Return(_a0 []filter.Sort, _a1 error) *MockParser_ParseSorts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParser_ParseSorts_Call) RunAndReturn(run func(*filter.SortConfig) ([]filter.Sort, error)) *MockParser_ParseSorts_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
