package builder

import "go.lumeweb.com/queryutil/filter"

// CompoundClause represents a logical grouping of multiple filter clauses.
// Used to implement AND/OR/NOT logical operations in database queries.
type CompoundClause struct {
	Operator filter.LogicalOperator // Logical operator (AND/OR/NOT)
	Filters  []filter.Clause        // Nested filter clauses
}

// Type identifies this as a compound clause for query building
func (cc *CompoundClause) Type() filter.ClauseType {
	return filter.CompoundClauseType
}

// SQLClause represents a concrete SQL condition with parameter bindings.
// Generated by the builder to be executed against a GORM database instance.
type SQLClause struct {
	Query  string        // SQL condition template (e.g. "name = ?")
	Params []interface{} // Parameter values to bind
	Field  string        // Original field name for debugging/validation
}

func NewSQLClause(operator string, value interface{}, field string) *SQLClause {
	return &SQLClause{
		Query:  operator,
		Params: []interface{}{value},
		Field:  field,
	}
}

func (sc *SQLClause) Type() filter.ClauseType {
	return filter.WhereClauseType
}

// ToSQL returns the SQL template and parameters for GORM Where() clause
func (sc *SQLClause) ToSQL() (string, []interface{}) {
	return sc.Query, sc.Params
}
