package builder

import "go.lumeweb.com/queryutil/filter"

// CompoundClause represents a logical combination of clauses (e.g., AND, OR, NOT).
// It's an internal representation built by the visitor methods.
type CompoundClause struct {
	Operator filter.LogicalOperator // AND, OR, NOT
	Filters  []filter.Clause        // The sub-clauses being combined
}

func NewCompoundClause(operator filter.LogicalOperator, filters []filter.Clause) *CompoundClause {
	return &CompoundClause{
		Operator: operator,
		Filters:  filters,
	}
}

func (cc *CompoundClause) Type() filter.ClauseType {
	return filter.CompoundClauseType
}

// SQLClause represents a single SQL condition with parameter bindings.
// Generated by the builder to be executed against a database.
type SQLClause struct {
	Query  string // SQL condition template (e.g. "name = ?", "BETWEEN ? AND ?")
	Params []any  // Parameter values to bind
	Field  string // Database column field name
}

// NewSQLClause creates a new SQLClause with variadic parameters
func NewSQLClause(query string, field string, params ...any) *SQLClause {
	return &SQLClause{
		Query:  query,
		Params: func() []any {
			if len(params) == 1 {
				if values, ok := params[0].([]any); ok {
					return values
				}
			}
			return params
		}(),
		Field:  field,
	}
}

func (sc *SQLClause) Type() filter.ClauseType {
	return filter.WhereClauseType
}
