// Code generated by mockery. DO NOT EDIT.

package builder

import (
	mock "github.com/stretchr/testify/mock"
	filter "go.lumeweb.com/queryutil/filter"
)

// MockQueryBuilder is an autogenerated mock type for the QueryBuilder type
type MockQueryBuilder struct {
	mock.Mock
}

type MockQueryBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryBuilder) EXPECT() *MockQueryBuilder_Expecter {
	return &MockQueryBuilder_Expecter{mock: &_m.Mock}
}

// VisitConditional provides a mock function with given fields: _a0
func (_m *MockQueryBuilder) VisitConditional(_a0 *filter.ConditionalFilter) (filter.Clause, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitConditional")
	}

	var r0 filter.Clause
	var r1 error
	if rf, ok := ret.Get(0).(func(*filter.ConditionalFilter) (filter.Clause, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*filter.ConditionalFilter) filter.Clause); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(filter.Clause)
		}
	}

	if rf, ok := ret.Get(1).(func(*filter.ConditionalFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueryBuilder_VisitConditional_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitConditional'
type MockQueryBuilder_VisitConditional_Call struct {
	*mock.Call
}

// VisitConditional is a helper method to define mock.On call
//   - _a0 *filter.ConditionalFilter
func (_e *MockQueryBuilder_Expecter) VisitConditional(_a0 interface{}) *MockQueryBuilder_VisitConditional_Call {
	return &MockQueryBuilder_VisitConditional_Call{Call: _e.mock.On("VisitConditional", _a0)}
}

func (_c *MockQueryBuilder_VisitConditional_Call) Run(run func(_a0 *filter.ConditionalFilter)) *MockQueryBuilder_VisitConditional_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*filter.ConditionalFilter))
	})
	return _c
}

func (_c *MockQueryBuilder_VisitConditional_Call) Return(_a0 filter.Clause, _a1 error) *MockQueryBuilder_VisitConditional_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueryBuilder_VisitConditional_Call) RunAndReturn(run func(*filter.ConditionalFilter) (filter.Clause, error)) *MockQueryBuilder_VisitConditional_Call {
	_c.Call.Return(run)
	return _c
}

// VisitLogical provides a mock function with given fields: _a0
func (_m *MockQueryBuilder) VisitLogical(_a0 *filter.LogicalFilter) (filter.Clause, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VisitLogical")
	}

	var r0 filter.Clause
	var r1 error
	if rf, ok := ret.Get(0).(func(*filter.LogicalFilter) (filter.Clause, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*filter.LogicalFilter) filter.Clause); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(filter.Clause)
		}
	}

	if rf, ok := ret.Get(1).(func(*filter.LogicalFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueryBuilder_VisitLogical_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VisitLogical'
type MockQueryBuilder_VisitLogical_Call struct {
	*mock.Call
}

// VisitLogical is a helper method to define mock.On call
//   - _a0 *filter.LogicalFilter
func (_e *MockQueryBuilder_Expecter) VisitLogical(_a0 interface{}) *MockQueryBuilder_VisitLogical_Call {
	return &MockQueryBuilder_VisitLogical_Call{Call: _e.mock.On("VisitLogical", _a0)}
}

func (_c *MockQueryBuilder_VisitLogical_Call) Run(run func(_a0 *filter.LogicalFilter)) *MockQueryBuilder_VisitLogical_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*filter.LogicalFilter))
	})
	return _c
}

func (_c *MockQueryBuilder_VisitLogical_Call) Return(_a0 filter.Clause, _a1 error) *MockQueryBuilder_VisitLogical_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueryBuilder_VisitLogical_Call) RunAndReturn(run func(*filter.LogicalFilter) (filter.Clause, error)) *MockQueryBuilder_VisitLogical_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueryBuilder creates a new instance of MockQueryBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryBuilder {
	mock := &MockQueryBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
